version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mazapay-app
    networks:
      - mazapay_api_network
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://admin:pass@mongo:27017
    ports:
      - '7070:7070'

  mongo:
    container_name: mazapay-mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mazapay_api_network

  mongo-express:
    container_name: mazapay-mongo-express
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
    networks:
      - mazapay_api_network

  redis:
    container_name: mazapay-redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - mazapay_api_network

networks:
  mazapay_api_network:
    driver: bridge
