services:
  mazapay_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7070:7070'
    environment:
      - PORT=7070
      - MONGO_URL=mongodb://admin:pass@mongo:27017/
      - DB_NAME=mazapay
      - SECRET_KEY=nopassword
 
    networks:
      - mazapay_api_network
    depends_on: 
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - mazapay_api_network


  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    depends_on:
      - mongo
    networks:
      - mazapay_api_network

networks:
  mazapay_api_network:
    driver: bridge